# Getting started with Julia and Machine Learning
## Anthony Blaom & Samuel
### JuliaCon 2022

## 1. Basic Julia

In [1]:
pwd()

"D:\\JULIA\\6. ML_with_Julia"

In [5]:
versioninfo()

Julia Version 1.8.0
Commit 5544a0fab7 (2022-08-17 13:38 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 12th Gen Intel(R) Core(TM) i7-1260P
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, goldmont)
  Threads: 1 on 16 virtual cores


In [7]:
# calculate
5 + 6 

11

In [8]:
sqrt(5 + 6)

3.3166247903554

In [9]:
sin(pi)

0.0

In [11]:
?sin

search: sin sinh sind sinc sinpi sincos sincosd sincospi asin using isinf asinh



```
sin(x)
```

Compute sine of `x`, where `x` is in radians.

See also [`sind`], [`sinpi`], [`sincos`], [`cis`].

---

```
sin(A::AbstractMatrix)
```

Compute the matrix sine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the sine. Otherwise, the sine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> sin(fill(1.0, (2,2)))
2×2 Matrix{Float64}:
 0.454649  0.454649
 0.454649  0.454649
```


In [12]:
v = [ 1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [13]:
length(v)

3

In [15]:
v[2]

2

In [16]:
v[2] = 42

42

In [17]:
v

3-element Vector{Int64}:
  1
 42
  3

In [18]:
row = [ 4 5 6 ]

1×3 Matrix{Int64}:
 4  5  6

In [19]:
A = [ 1 2 3 
    4 5 6 ; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [20]:
A[2, 3]

6

In [22]:
length(A)

9

In [23]:
size(A)

(3, 3)

In [24]:
inv(A)

LoadError: LinearAlgebra.SingularException(3)

In [25]:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.553643  0.124852  0.378498
 0.56792   0.227348  0.380484
 0.136927  0.768574  0.798599

In [26]:
inv(A)

3×3 Matrix{Float64}:
 -2.64457   4.56057  -0.919436
 -9.57553   9.31004   0.102673
  9.66894  -9.74196   1.31103

In [27]:
A'

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 0.553643  0.56792   0.136927
 0.124852  0.227348  0.768574
 0.378498  0.380484  0.798599

In [28]:
using LinearAlgebra

In [29]:
svd(A)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
 -0.428396  -0.575431  -0.696675
 -0.475665  -0.511918   0.715321
 -0.768258   0.637824  -0.0544086
singular values:
3-element Vector{Float64}:
 1.3623544627899684
 0.6107571610299938
 0.050385059023472074
Vt factor:
3×3 Matrix{Float64}:
 -0.449599  -0.552052  -0.702211
 -0.854638   0.494448   0.158476
  0.25972    0.671387  -0.694108

In [30]:
sqrt(9)

3.0

In [31]:
3 == 3.0

true

In [32]:
3 === 3.0

false

In [33]:
u = [1, 3, 5]

3-element Vector{Int64}:
 1
 3
 5

In [34]:
w = u

3-element Vector{Int64}:
 1
 3
 5

In [35]:
u[2] = 42

42

In [36]:
w

3-element Vector{Int64}:
  1
 42
  5

In [37]:
t1 = (1, 5.7, "cat")

(1, 5.7, "cat")

In [38]:
t1[3]

"cat"

In [39]:
t1[3] = "dog"

LoadError: MethodError: no method matching setindex!(::Tuple{Int64, Float64, String}, ::String, ::Int64)

In [40]:
t1 = (x = 1, y = 5.7, z = "cat")

(x = 1, y = 5.7, z = "cat")

In [41]:
t1.x

1

In [42]:
astring = "cat"

"cat"

In [43]:
astring[3]

't': ASCII/Unicode U+0074 (category Ll: Letter, lowercase)

In [44]:
achar = 'c'

'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)

In [45]:
asymbol = :cat

:cat

In [46]:
foo(x) = x^2

foo (generic function with 1 method)

In [47]:
foo(3)

9

In [48]:
x -> x^2

#1 (generic function with 1 method)

In [49]:
3 |> foo

9

In [50]:
3 |> x -> x^2

9

In [51]:
3 |> x -> x^2 |> foo

81

In [52]:
function foo2(x)
    x = x^3
    y = x
    w = y
    return w
end

foo2 (generic function with 1 method)

In [53]:
foo2(2)

8

In [54]:
squares = [] 

Any[]

In [55]:
for x in 1:10
    push!(squares, x^2)
end

In [56]:
squares

10-element Vector{Any}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [57]:
[x^2 for x in 1:10]

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [58]:
map(x -> x^2, 1:10)

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [62]:
(1:10).^2 # perfom operation with element-wise

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [63]:
rand()

0.6685834289323005

In [64]:
rand(3, 4)

3×4 Matrix{Float64}:
 0.273885  0.385241   0.792252  0.28639
 0.64432   0.0197783  0.353029  0.190647
 0.667554  0.0166292  0.464048  0.57507

In [65]:
randn(3, 4)

3×4 Matrix{Float64}:
 0.133879  -1.59311   -0.697165  0.275738
 0.709255  -1.38227   -0.969661  0.0198106
 2.27803    0.778215   0.271902  0.507985

In [66]:
rand(3)

3-element Vector{Float64}:
 0.15991680699954947
 0.45374438324573463
 0.9646323061998026

In [68]:
rand(['a', 'b', 'c'], 10)

10-element Vector{Char}:
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [69]:
rand(['멀', '가', '중'], 10)

10-element Vector{Char}:
 '중': Unicode U+C911 (category Lo: Letter, other)
 '중': Unicode U+C911 (category Lo: Letter, other)
 '멀': Unicode U+BA40 (category Lo: Letter, other)
 '멀': Unicode U+BA40 (category Lo: Letter, other)
 '멀': Unicode U+BA40 (category Lo: Letter, other)
 '중': Unicode U+C911 (category Lo: Letter, other)
 '중': Unicode U+C911 (category Lo: Letter, other)
 '가': Unicode U+AC00 (category Lo: Letter, other)
 '중': Unicode U+C911 (category Lo: Letter, other)
 '중': Unicode U+C911 (category Lo: Letter, other)

In [70]:
using Statistics

In [71]:
mean(rand(100))

0.4935803308082482

**Q&A** 
 - push vs append
 
     - push는 element, append는 vector 단위로 입력함